CREATE TABLE IF NOT EXISTS `mmapi_schema`.`api_timestamp_data_fromExcel` (
    `roomNum` VARCHAR(45) NULL,
    `studyID` INT NULL,
    `scheduleServiceDate` DATETIME NULL,
    `Month` VARCHAR(3) NULL,
    `DayOfWeek` VARCHAR(3) NULL,
    `Year` INT NULL,
    `Qtr` VARCHAR(2) NULL,
    `procedureType` VARCHAR(5) NULL,
    `Radiology Exam` VARCHAR(45) NULL,
    `servicePriority` VARCHAR(45) NULL,
    `examComments` VARCHAR(45) NULL,
    `techComments` VARCHAR(45) NULL,
    `facilityName` VARCHAR(45) NULL,
    `techLast` VARCHAR(45) NULL,
    `techFirst` VARCHAR(45) NULL,
    `Tech Name` VARCHAR(45) NULL,
    `regionName` VARCHAR(45) NULL,
    `corpName` VARCHAR(45) NULL,
    `referLast` VARCHAR(45) NULL,
    `referFirst` VARCHAR(45) NULL,
    `Referring Physician` VARCHAR(45) NULL,
    `physicianID` INT NULL,
    `taxonomyCode` VARCHAR(45) NULL,
    `firstReport_docID` INT NULL,
    `orderTS` VARCHAR(45) NULL,
    `DateofOrder` VARCHAR(45) NULL,
    `TImeOfOrder` DATETIME NULL,
    `shift` VARCHAR(10) NULL,
    `orderAssignedTS` DATETIME NULL,
    `TechArrivalTS` DATETIME NULL,
    `orderCompleteTS` DATETIME NULL,
    `firstImage_uploadTS` DATETIME NULL,
    `firstReport_transcribeTS` DATETIME NULL,
    `TAT-Script_Report` VARCHAR(45) NULL,
    `TAT-Script_Tech Completed` VARCHAR(45) NULL,
    `firstReport_reviewedByDoctor` VARCHAR(45) NULL,
    `firstReport_faxedTS` VARCHAR(45) NULL,
    `firstReport_resultsPhonedTS` VARCHAR(45) NULL,
    `CritFindings` VARCHAR(45) NULL,
    `no._seen` VARCHAR(45) NULL
)  ENGINE=INNODB